sudo: false
language: python
python:
- 3.6.9
before_install:
- pip install poetry
install:
- poetry install
script:
- make lint
- make docs
- make test
after_success:
- poetry run codecov
env:
  global:
  - secure: QDyhVVR/VGaxZZLzmxuRe+apwevyFP8c4ZlL5gwTv3wVmD0kgzTVigM9FCqo2z/Rhh+qvyY8lEzFYjHtMczk7QHxXJFyLCpQ5DTFp9TQHQW4kXC1SAJWBjtg2imIrle6zmwioqoRsfyGIOnXCEV9fM9Sfw6jROXXydWW5/wqDlvmC8awPVUpt5wPpRjz0yZIJsDBy7IVbKR26UxfT3NZew7tTaoLY6rcCscAGakoNnjtkJURJEWlx+Vvai/eQAyKOLeAZbS8Y3kx9txcXvFgUheQGHJ8mP+fs7XM6aVtLEa3VIO+X/hwe7pBB4YX01m6JHIZU4jyuCr8qEoszQ9Ef1Ie27xAPdhtoeCFJNQwaMO4bm7egPK9D/4AzjIMZxtukuoIsXmciTwFRri8jQYwLh+/vUSA/l2+fDsVvxbkr0L6f5sj76Gb6eTxYpqAo9ZMMcV2UjshW+Y8wV6RuYP4xTI2VM4sjUG9C7HdUFLqDuohGtINXL0unxGJMQ5TwzVudScBa6hu54rf6ArpPGIr3ERC2hz3SfbvBPLYuuHqRR0SqLW2TFQo2cp1hgNjspJJVzPt09ppnHmwdqv5c0vZEnqi1QwDsAtDF6oO7PQ4rayXjssVSIJ7M9b3eKEQT7Xyvc7UIUDO2JfSfZJFvw0P/LQMAEc1x/BIS9aqU4xeC9w=
  - secure: TCS8YbhpbEOKxQuszCIgNcQnMBRn2OanCvIq3A5N3P5wM+fhcAMVeu28hr0NhuxtgipxCdV0iXTr2uM9lbPtkdNJM71naIK0mjRbfnKmRfsQ67f9y3y79lE59IXXhCyMHgtov0quVePO4dTrsOm/qvWIuXM/BDBzdeY/tLAM7aGnwHWEt16nJogNz3c6JNazCkb5i4+BMWsieuJWAlRlgPa/dyZN7qcFvhNs5n5B8rcGDukWkV2lGJ8s2UW4wOvS9+sqAgDszeBIseXUXJoQQi9rE63tG4WXOaMYuFhGOFeZTjA49IGYt/9aZCGwaUrcpzTiatJuDl0jvbMT/ID+2F33LB5wByyim/MgQubjJDe6JDBVitxe+Os1JyDer3gY9N/B0PWSdDAo7+nSriFn4oo0vohivKbu/HvgXymvqcQyKHOKqG2ckSvnwdwNwSqQahuSAPuqyLRZ//iSkF5gCJ/XHeWEzMKY+KhXuoZwCatqie2/o6QZDB4KixF1zmtb8wLr4POU8e4EsuFjACqgKkI16kJY0jJTWt4raApbax50KRTlOVdyJAjo2J9U03+rkBVaVmd3SGkfc7TkRAL8f+qCCjMyQRLXbq1+rRHo7jCzMdfuzmXysoAVRczEuzDJauv84XxWVjaTxskOZ8D8knschMVdg+/ws+ZccvcNMNM=
  - secure: Gygyl5Evlu9gY1B8+O5qZG3cRgrsFgqlbjWYQhvq97BtJPjy0slbcXXwoI/WztDjWa9NqjLxWUYORFL43cO+Gi7ijyb6w2riYGq1Ao8457RJhu86t223/8TnWk+T7P+cCn7FD5rF3TyWuKkPudPpeLgq0ja4Q89m1/XnTV/4LENzQJZ+d0Fo+KMXnZ4NNDupMUgGsugWF44rIkbjsMPN2nWYf1wif/MLBKjinBKMrMiAAu3ymZj6Jy2+oOLIFfosFkNFua8Uv3FTRBm85F9Ddcij5MwL22j9w+M4rNYvdkgEusDZOIQlx2GZn5dFvMSQ2Eqhs3Y11vAqRrE3P+STny+wTdtUil9Vhug9ys1QNya/mOMw8/KAA3CROEi5gc/VaPJLBELNaY0VW50UIlMfpVbLJOG6aSxDp00kewi74XKGpfN73IZVGbosbvf5o1dQcX3eDyASARQZ+f7YzTWudyUHNfTUGmMzTHVfs23ozQPchFCeQfTg/Wo0L5e23zK1qUS/uO1XN4VD90AXcXFsod1oYcumqpJgKuha7s7K0yKTkHMnQJHVOpi8Vl0AgZUI9s+pF0l+oRRY4BtU2k3/+vIDTKWcxDhrwQldsu4kDFohk29Gpao3sXbt9t70An+Cg7pvY8upQ5BK9aqLh6E9EfplvZJXWlu7CKidbckhjWw=
