# Disable sudo to speed up the build
sudo: false

language: python

python:
- 3.6.9

before_install:
- pip install poetry

install:
- poetry install

script:
- poetry run mypy .
- poetry run flake8
- poetry run black . --check
- poetry run python -m pytest --cov=ergo -s .

after_success:
  - poetry run codecov
